/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject
import it.unibo.Hold.Hold
import it.unibo.Hold.HoldState


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var hold = Hold()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("[CARGO SERVICE] started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGO SERVICE] DISENGAGED: waiting for load_requests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] evaluating load request...")
						val currentHoldState = hold.getState()
						if( currentHoldState != HoldState.DISENGAGED ) {
							CommUtils.outcyan("[CARGO SERVICE] another container is being moved, replying with RETRY LATER.")
							answer("load_request", "retrylater", "retrylater($currentHoldState)"   )
						} else {
							val slotToFill = hold.nextFreeSlot()
							if( slotToFill == null ) {
								CommUtils.outcyan("[CARGO SERVICE] all slots are taken, replying with REFUSED.")
								answer("load_request", "load_refused", "load_refused(none)"   )
							} else {
								CommUtils.outcyan("[CARGO SERVICE] setting holdstate to ENGAGED, replying with ACCEPTED and waiting for sonar message.")
								hold.setState(HoldState.ENGAGED)
								val intSlotToFill = slotToFill.getId()
								answer("load_request", "load_accepted", "load_accepted($intSlotToFill)"   )
								delay(5000)
								CommUtils.outblack("Make the robot work to load the container in the designated spot")
							}
						}

						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("switch_to_disengaged") { //this:State
					action { //it:State
						 hold.setState(HoldState.DISENGAGED)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
