/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				fun LoadDistances(): List<Int> {
					val fallback = listOf(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1)
					// NOTE: the comment character of the table file is produced at runtime
					// (35.toChar()): that literal character must NOT appear inside a qak
					// expression block, or the editor mis-detects the end of the block
					val commentChar = 35.toChar()
					return try {
						val vals = java.io.File("sonarDistances.txt").readLines()
							.map { line -> line.substringBefore(commentChar).trim() }
							.filter { line -> line.isNotEmpty() }
							.flatMap { line -> line.split(",").map { p -> p.trim() } }
							.filter { p -> p.isNotEmpty() }
							.map { p -> p.toInt() }
						if (vals.isEmpty()) fallback else vals
					} catch (e: Exception) { fallback }
				}
				val Distances = LoadDistances()
				var MeasureIdx = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[SONAR] proactive publisher started (table of {Distances.size} distances, cyclic)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="do_publish", cond=doswitch() )
				}	 
				state("do_publish") { //this:State
					action { //it:State
						 val D = Distances[MeasureIdx % Distances.size]  
						 MeasureIdx = MeasureIdx + 1  
						emit("sonar_distance", "sonar_distance($D)" ) 
						delay(1000) 
						forward("sonar_next_measure", "sonar_next_measure(none)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="do_publish",cond=whenDispatch("sonar_next_measure"))
				}	 
			}
		}
} 
