/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "waiting"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				val DFREE  = 3
				var CurrD = 0
		return { //this:ActionBasciFsm
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outyellow("[SONAR] ready!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="measureDistance",cond=whenDispatch("checkMeasurement"))
				}	 
				state("measureDistance") { //this:State
					action { //it:State
						CommUtils.outyellow("[SONAR] measuring distance...")
						 CurrD = Random.nextInt(0, 6)  
						if(  currD > DFREE  
						 ){delay(3000) 
						 CurrD = Random.nextInt(0, 6)  
						if(  currD > DFREE  
						 ){CommUtils.outblack("[SONAR] send message to cargoservice that the hold is out of service")
						emit("outOfService", "outOfService(none)" ) 
						}
						else
						 {emit("containerPositioned", "containerPositioned(none)" ) 
						 }
						}
						else
						 {if(  CurrD < DFREE / 2  
						  ){emit("containerPositioned", "containerPositioned(none)" ) 
						 }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
