/* Generated by AN DISI Unibo */
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

// proactive detector (committente answer Q5): publishes on its own initiative
// the distances read (in cyclic order) from the statically configurable table
// sonarDistances.txt — deterministic, reproducible prototype runs. The physical
// pico sonar will publish really-measured distances on the same contract.
class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) :
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){

			fun LoadDistances(): List<Int> {
				val fallback = listOf(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1)
				return try {
					val vals = java.io.File("sonarDistances.txt").readLines()
						.map { line -> line.substringBefore('#').trim() }
						.filter { line -> line.isNotEmpty() }
						.flatMap { line -> line.split(',').map { p -> p.trim() } }
						.filter { p -> p.isNotEmpty() }
						.map { p -> p.toInt() }
					if (vals.isEmpty()) fallback else vals
				} catch (e: Exception) { fallback }
			}
			val Distances = LoadDistances()
			var MeasureIdx = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[SONAR] proactive publisher started (table of ${Distances.size} distances, cyclic)")
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="publish", cond=doswitch() )
				}
				state("publish") { //this:State
					action { //it:State
						 val D = Distances[MeasureIdx % Distances.size]
						 MeasureIdx = MeasureIdx + 1
						CommUtils.outyellow("[SONAR] D=$D")
						emit("sonar_distance", "sonar_distance($D)" )
						delay(1000)
						forward("sonar_next_measure", "sonar_next_measure(none)" ,name )
					}
					sysaction { //it:State
					}
					 transition(edgeName="t030",targetState="publish",cond=whenDispatch("sonar_next_measure"))
				}
			}
		}
}
