/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import it.unibo.Hold.*

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var CurrentHoldState: HoldState = HoldState.DISENGAGED
				var CurrentSlotToFill: ISlot? = null
				var windowJob: kotlinx.coroutines.Job? = null
		
				// DFREE in centimetres (deployment constant; committente question open).
				// presence: D < DFREE/2 (=15 cm); failure: D > DFREE (=30 cm)
				val DFREE = 30
		
				var SlotsList: List<ISlot> = listOf(
					Slot(1, 1, 2),
					Slot(2, 1, 5),
					Slot(3, 3, 2),
					Slot(4, 3, 5)
				)
				var IOPortX = 6
				var IOPortY = 1
				var HomeX   = 0
				var HomeY   = 0
				var Slot5X  = 2
				var Slot5Y  = 6
		
				fun FindFirstFreeSlot(slots: List<ISlot>): ISlot? =
					slots.firstOrNull { slot -> slot.content == null }
		
				fun slotAtom(slot: ISlot): String =
					if (slot.content != null) "occupied"
					else if (CurrentSlotToFill != null && CurrentSlotToFill!!.id == slot.id) "reserved"
					else "free"
		
				fun reservedAtom(): String =
					if (CurrentSlotToFill != null) CurrentSlotToFill!!.id.toString() else "none"
		
				fun stateAtom(): String = when (CurrentHoldState) {
					HoldState.DISENGAGED     -> "disengaged"
					HoldState.ENGAGED        -> "engaged"
					HoldState.OUT_OF_SERVICE -> "outofservice"
				}
		
				fun workingAtom(): String =
					if (CurrentHoldState == HoldState.OUT_OF_SERVICE) "outofservice" else "working"
		
				fun ApplyPreset(config: String) {
					for (slot in SlotsList) slot.content = if (config == "full") Container() else null
					CurrentSlotToFill = null
					CurrentHoldState = HoldState.DISENGAGED
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("[CARGO SERVICE] started - subscribing to the boundary topic load_requests")
						subscribe(  "load_requests" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGO SERVICE] hold ${'$'}CurrentHoldState: waiting for load_requests")
						 val St = stateAtom(); val Wk = workingAtom();
								   val A1 = slotAtom(SlotsList[0]); val A2 = slotAtom(SlotsList[1]);
								   val A3 = slotAtom(SlotsList[2]); val A4 = slotAtom(SlotsList[3]);
								   val R  = reservedAtom()  
						//val m = MsgUtil.buildEvent(name, "holdstatus", "holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)" ) 
						publish(MsgUtil.buildEvent(name,"holdstatus","holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)").toString(), "hold_state" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenDispatch("load_request"))
					transition(edgeName="t01",targetState="serve_preset_hold",cond=whenRequest("preset_hold"))
				}	 
				state("serve_preset_hold") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("preset_hold(HOLDCONFIG)"), Term.createTerm("preset_hold(HOLDCONFIG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Config = payloadArg(0); ApplyPreset(Config)  
								answer("preset_hold", "preset_done", "preset_done(done)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] evaluating load request...")
						if(  CurrentHoldState != HoldState.DISENGAGED  
						 ){CommUtils.outcyan("[CARGO SERVICE] busy / out of service -> retrylater (state pushed)")
						forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name ) 
						}
						else
						 { CurrentSlotToFill = FindFirstFreeSlot(SlotsList)  
						 if(  CurrentSlotToFill == null  
						  ){CommUtils.outcyan("[CARGO SERVICE] hold full -> refused (state pushed)")
						 forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name ) 
						 }
						 else
						  {CommUtils.outcyan("[CARGO SERVICE] ENGAGED: reserve slot, blink LED, open sonar listening")
						   CurrentHoldState = HoldState.ENGAGED  
						  forward("cargoservice_goto_accept", "cargoservice_goto_accept(none)" ,name ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="accept_load_request",cond=whenDispatch("cargoservice_goto_accept"))
					transition(edgeName="t03",targetState="waiting",cond=whenDispatch("cargoservice_goto_waiting"))
				}	 
				state("accept_load_request") { //this:State
					action { //it:State
						 publish("start_blinking", "led_data")  
						forward("start_detection", "start_detection(none)" ,"sonar" ) 
						
									windowJob?.cancel()
									windowJob = kotlinx.coroutines.GlobalScope.launch {
										kotlinx.coroutines.delay(30000L)
										forward("cargoservice_window_expired", "cargoservice_window_expired(none)", "cargoservice")
									}
						 val St = stateAtom(); val Wk = workingAtom();
								   val A1 = slotAtom(SlotsList[0]); val A2 = slotAtom(SlotsList[1]);
								   val A3 = slotAtom(SlotsList[2]); val A4 = slotAtom(SlotsList[3]);
								   val R  = reservedAtom()  
						//val m = MsgUtil.buildEvent(name, "holdstatus", "holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)" ) 
						publish(MsgUtil.buildEvent(name,"holdstatus","holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)").toString(), "hold_state" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="window_expired",cond=whenDispatch("cargoservice_window_expired"))
					transition(edgeName="t05",targetState="start_trip",cond=whenEvent("container_detected"))
					transition(edgeName="t06",targetState="sonar_out_of_service",cond=whenEvent("out_of_service"))
					transition(edgeName="t07",targetState="engaged_retrylater",cond=whenDispatch("load_request"))
				}	 
				state("engaged_retrylater") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] engaged: pushing busy state to a concurrent request")
						 val St = stateAtom(); val Wk = workingAtom();
								   val A1 = slotAtom(SlotsList[0]); val A2 = slotAtom(SlotsList[1]);
								   val A3 = slotAtom(SlotsList[2]); val A4 = slotAtom(SlotsList[3]);
								   val R  = reservedAtom()  
						//val m = MsgUtil.buildEvent(name, "holdstatus", "holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)" ) 
						publish(MsgUtil.buildEvent(name,"holdstatus","holdstatus($St,$Wk,$A1,$A2,$A3,$A4,$R)").toString(), "hold_state" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged_window", cond=doswitch() )
				}	 
				state("engaged_window") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGO SERVICE] engaged: window open, listening to the logic sonar")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="window_expired",cond=whenDispatch("cargoservice_window_expired"))
					transition(edgeName="t09",targetState="start_trip",cond=whenEvent("container_detected"))
					transition(edgeName="t010",targetState="sonar_out_of_service",cond=whenEvent("out_of_service"))
					transition(edgeName="t011",targetState="engaged_retrylater",cond=whenDispatch("load_request"))
				}	 
				state("window_expired") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] 30s window expired: discard reservation, LED off, close listening")
						 publish("stop_blinking", "led_data")  
						forward("stop_detection", "stop_detection(none)" ,"sonar" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="switch_to_disengaged", cond=doswitch() )
				}	 
				state("sonar_out_of_service") { //this:State
					action { //it:State
						CommUtils.outred("[CARGO SERVICE] SONAR FAILURE during the window -> OUT OF SERVICE (terminal)")
						 windowJob?.cancel()  
						 publish("stop_blinking", "led_data")  
						forward("stop_detection", "stop_detection(none)" ,"sonar" ) 
						 CurrentSlotToFill = null; CurrentHoldState = HoldState.OUT_OF_SERVICE  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("start_trip") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] container detected: LED off, close listening, start the trip")
						 windowJob?.cancel()  
						 publish("stop_blinking", "led_data")  
						forward("stop_detection", "stop_detection(none)" ,"sonar" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="move_to_ioport", cond=doswitch() )
				}	 
				state("move_to_ioport") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] robot -> IOPort")
						request("reachTarget", "reachTarget($IOPortX,$IOPortY)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="move_to_slot5",cond=whenReply("targetReached"))
					transition(edgeName="t013",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}	 
				state("move_to_slot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] robot -> slot5 (marking)")
						request("reachTarget", "reachTarget($Slot5X,$Slot5Y)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="marking_pause",cond=whenReply("targetReached"))
					transition(edgeName="t015",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}	 
				state("marking_pause") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] marker device (emulated ~5 s pause)")
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="move_to_reserved_slot", cond=doswitch() )
				}	 
				state("move_to_reserved_slot") { //this:State
					action { //it:State
						 val Rx = CurrentSlotToFill!!.x; val Ry = CurrentSlotToFill!!.y  
						CommUtils.outmagenta("[CARGO SERVICE] robot -> reserved slot")
						request("reachTarget", "reachTarget($Rx,$Ry)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="container_stored",cond=whenReply("targetReached"))
					transition(edgeName="t017",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}	 
				state("container_stored") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] container stored: mark slot occupied, robot -> HOME")
						 CurrentSlotToFill!!.content = Container()  
						request("reachTarget", "reachTarget($HomeX,$HomeY)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="switch_to_disengaged",cond=whenReply("targetReached"))
					transition(edgeName="t019",targetState="switch_to_disengaged",cond=whenReply("targetUnreachable"))
				}	 
				state("abort_transfer") { //this:State
					action { //it:State
						CommUtils.outred("[CARGO SERVICE] robot failure -> hold OUT OF SERVICE (terminal)")
						 CurrentSlotToFill = null; CurrentHoldState = HoldState.OUT_OF_SERVICE  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("switch_to_disengaged") { //this:State
					action { //it:State
						 CurrentSlotToFill = null; CurrentHoldState = HoldState.DISENGAGED  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
