/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				// last raw distance seen on sonar_data (cm); shared with the MQTT callback thread
				val lastDistance = java.util.concurrent.atomic.AtomicReference<Double>(java.lang.Double.MAX_VALUE)
				var mqttIn: org.eclipse.paho.client.mqttv3.MqttClient? = null
		
				val DFREE = 30                 // must match cargoservice
				val PERSISTENCE = 3            // 3 consecutive seconds at the 1 Hz device rate
				var presenceCount = 0
				var failureCount  = 0
		
				fun ensureSubscribed() {
					if (mqttIn != null) return
					try {
						val cli = org.eclipse.paho.client.mqttv3.MqttClient(
							"tcp://localhost:1883", "logicSonarIn_" + System.currentTimeMillis(),
							org.eclipse.paho.client.mqttv3.persist.MemoryPersistence())
						val opts = org.eclipse.paho.client.mqttv3.MqttConnectOptions()
						opts.isCleanSession = true
						cli.connect(opts)
						cli.subscribe("sonar_data") { _, message ->
							val s = String(message.payload).trim()
							val d = s.toDoubleOrNull()
							if (d != null) lastDistance.set(d)
						}
						mqttIn = cli
					} catch (e: Exception) {
						println("[LOGIC SONAR] MQTT subscribe error: " + e.message)
					}
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[LOGIC SONAR] started (idle: listening closed)")
						 ensureSubscribed()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 presenceCount = 0; failureCount = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="observing",cond=whenDispatch("start_detection"))
				}	 
				state("observing") { //this:State
					action { //it:State
						forward("sonar_tick", "sonar_tick(none)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="idle",cond=whenDispatch("stop_detection"))
					transition(edgeName="t022",targetState="eval_measure",cond=whenDispatch("sonar_tick"))
				}	 
				state("eval_measure") { //this:State
					action { //it:State
						
									val d = lastDistance.get()
									if (d < DFREE / 2.0) { presenceCount += 1; failureCount = 0 }
									else if (d > DFREE)  { failureCount  += 1; presenceCount = 0 }
									else { presenceCount = 0; failureCount = 0 }
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="emit_detected", cond=doswitchGuarded({ presenceCount >= PERSISTENCE  
					}) )
					transition( edgeName="goto",targetState="check_failure", cond=doswitchGuarded({! ( presenceCount >= PERSISTENCE  
					) }) )
				}	 
				state("check_failure") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="emit_failure", cond=doswitchGuarded({ failureCount >= PERSISTENCE  
					}) )
					transition( edgeName="goto",targetState="observing", cond=doswitchGuarded({! ( failureCount >= PERSISTENCE  
					) }) )
				}	 
				state("emit_detected") { //this:State
					action { //it:State
						CommUtils.outgreen("[LOGIC SONAR] presence sustained -> container_detected")
						 presenceCount = 0; failureCount = 0  
						emit("container_detected", "container_detected(none)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observing", cond=doswitch() )
				}	 
				state("emit_failure") { //this:State
					action { //it:State
						CommUtils.outred("[LOGIC SONAR] failure sustained (D>DFREE 3s) -> out_of_service")
						 presenceCount = 0; failureCount = 0  
						emit("out_of_service", "out_of_service(none)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observing", cond=doswitch() )
				}	 
			}
		}
} 
