/* Generated by AN DISI Unibo */
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import it.unibo.Hold.*

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) :
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF


		        var CurrentHoldState: HoldState = HoldState.DISENGAGED

		        var CurrentSlotToFill: ISlot? = null

				var IOPortX = 6
				var IOPortY = 1

				var HomeX = 0
				var HomeY = 0

				var Slot5X = 2
				var Slot5Y = 6


				var SlotsList: List<ISlot> = listOf(
					Slot(1, 1, 2),
			        Slot(2, 1, 5),
			        Slot(3, 3, 2),
			        Slot(4, 3, 5)
			    )

			    fun FindFirstFreeSlot(slots: List<ISlot>): ISlot? {
				    return slots.firstOrNull { slot -> slot.content == null }
				}

				// observable description of the hold (P5): all lowercase so that the
				// payload is a legal message atom, e.g. disengaged_free_occupied_free_free
				fun DescribeHold(): String {
					val slotsDesc = SlotsList.joinToString("_") { slot -> if (slot.content == null) "free" else "occupied" }
					return CurrentHoldState.toString().lowercase() + "_" + slotsDesc
				}

				// controllable Given for the TestPlans (P5): preset_hold(full) / preset_hold(empty)
				fun ApplyPreset(config: String) {
					for (slot in SlotsList) {
						slot.content = if (config == "full") Container() else null
					}
					CurrentSlotToFill = null
					CurrentHoldState = HoldState.DISENGAGED
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("[CARGO SERVICE] started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGO SERVICE] DISENGAGED: waiting for load_requests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="serve_get_hold",cond=whenRequest("get_hold"))
					transition(edgeName="t02",targetState="serve_preset_hold",cond=whenRequest("preset_hold"))
				}
				state("serve_get_hold") { //this:State
					action { //it:State
						// test support (P5): observation, served at quiescent points
						val HoldDescription = DescribeHold()
						answer("get_hold", "hold_state", "hold_state($HoldDescription)"   )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}
				state("serve_preset_hold") { //this:State
					action { //it:State
						// test support (P5): controllable Given
						if( checkMsgContent( Term.createTerm("preset_hold(HOLDCONFIG)"), Term.createTerm("preset_hold(HOLDCONFIG)"),
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Config = payloadArg(0)
								 ApplyPreset(Config)
								answer("preset_hold", "preset_done", "preset_done(done)"   )
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] evaluating load request...")
						// P1: the three answer branches are MUTUALLY EXCLUSIVE: exactly one reply per request
						if(  CurrentHoldState != HoldState.DISENGAGED
						 ){CommUtils.outcyan("[CARGO SERVICE] another container is being moved or the hold is 'out of service', replying with RETRY LATER.")
						 val CurrentHoldStateLc = CurrentHoldState.toString().lowercase()
						answer("load_request", "load_retrylater", "load_retrylater($CurrentHoldStateLc)"   )
						forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name )
						}
						else
						 {
						 CurrentSlotToFill = FindFirstFreeSlot(SlotsList)
						if(  CurrentSlotToFill == null
						 ){CommUtils.outcyan("[CARGO SERVICE] all slots are taken, replying with REFUSED.")
						answer("load_request", "load_refused", "load_refused(none)"   )
						forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name )
						}
						else
						 {CommUtils.outcyan("[CARGO SERVICE] setting holdstate to ENGAGED, replying with ACCEPTED and waiting for sonar message.")
						  CurrentHoldState = HoldState.ENGAGED
						  var CurrentSlotToFillId = CurrentSlotToFill!!.id
						 answer("load_request", "load_accepted", "load_accepted($CurrentSlotToFillId)"   )
						 forward("cargoservice_goto_accept_load_request", "cargoservice_goto_accept_load_request(none)" ,name )
						 }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t03",targetState="accept_load_request",cond=whenDispatch("cargoservice_goto_accept_load_request"))
					transition(edgeName="t04",targetState="waiting",cond=whenDispatch("cargoservice_goto_waiting"))
				}
				state("accept_load_request") { //this:State
					action { //it:State
						forward("checkMeasurement", "checkMeasurement(none)" ,"sonar" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		// NOTE: the timeout-event suffix must NOT contain '_' —
				 	 		// TimerActor resolves its owner with substringBeforeLast("_"),
				 	 		// so "local_tout_cargoservice_accept_load_request" would loop
				 	 		// forever looking for an actor named "cargoservice_accept_load"
				 	 		stateTimer = TimerActor("timer_accept_load_request",
				 	 					  scope, context!!, "local_tout_"+name+"_w30accept", 30000.toLong() )  //OCT2023
					}
					 transition(edgeName="t05",targetState="switch_to_disengaged",cond=whenTimeout("local_tout_"+name+"_w30accept"))
					transition(edgeName="t06",targetState="move_to_ioport",cond=whenEvent("containerPositioned"))
					transition(edgeName="t07",targetState="engaged_retrylater",cond=whenRequest("load_request"))
				}
				state("engaged_retrylater") { //this:State
					action { //it:State
						// a request received while engaged is answered retrylater (committente
						// question 3); served in a twin state so that the sonar is not re-triggered
						CommUtils.outcyan("[CARGO SERVICE] engaged: replying RETRY LATER to a concurrent request")
						 val CurrentHoldStateLc = CurrentHoldState.toString().lowercase()
						answer("load_request", "load_retrylater", "load_retrylater($CurrentHoldStateLc)"   )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="engaged_window", cond=doswitch() )
				}
				state("engaged_window") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] still engaged, waiting for the container detection")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		// same TimerActor naming constraint as above: no '_' in the suffix
				 	 		stateTimer = TimerActor("timer_engaged_window",
				 	 					  scope, context!!, "local_tout_"+name+"_w30window", 30000.toLong() )  //OCT2023
					}
					 transition(edgeName="t08",targetState="switch_to_disengaged",cond=whenTimeout("local_tout_"+name+"_w30window"))
					transition(edgeName="t09",targetState="move_to_ioport",cond=whenEvent("containerPositioned"))
					transition(edgeName="t010",targetState="engaged_retrylater",cond=whenRequest("load_request"))
				}
				state("move_to_ioport") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] Command: Moving robot to IOPort")
						request("reachTarget", "reachTarget($IOPortX,$IOPortY)" ,"cargorobot" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t011",targetState="move_to_slot5",cond=whenReply("targetReached"))
					transition(edgeName="t012",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}
				state("move_to_slot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("[CARGO SERVICE] Command: Moving robot to Slot5")
						request("reachTarget", "reachTarget($Slot5X,$Slot5Y)" ,"cargorobot" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t013",targetState="marking_pause",cond=whenReply("targetReached"))
					transition(edgeName="t014",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}
				state("marking_pause") { //this:State
					action { //it:State
						// marker device emulated by a ~5 s delay (committente clarification)
						CommUtils.outmagenta("[CARGO SERVICE] waiting for marker device delay...")
						delay(5000)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="move_to_reserved_slot", cond=doswitch() )
				}
				state("move_to_reserved_slot") { //this:State
					action { //it:State

						    		var CurrentSlotToFillX = CurrentSlotToFill!!.x
						    		var CurrentSlotToFillY = CurrentSlotToFill!!.y
						CommUtils.outmagenta("[CARGO SERVICE] Command: Moving robot to the reserved Slot")
						request("reachTarget", "reachTarget($CurrentSlotToFillX,$CurrentSlotToFillY)" ,"cargorobot" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t015",targetState="container_stored",cond=whenReply("targetReached"))
					transition(edgeName="t016",targetState="abort_transfer",cond=whenReply("targetUnreachable"))
				}
				state("container_stored") { //this:State
					action { //it:State
						// mark the RESERVED slot occupied, then send the robot HOME (Q2):
						// if only this last movement fails, the load is completed anyway
						CommUtils.outmagenta("[CARGO SERVICE] container stored: marking the reserved slot occupied, sending robot HOME")
						 CurrentSlotToFill!!.content = Container()
						request("reachTarget", "reachTarget($HomeX,$HomeY)" ,"cargorobot" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition(edgeName="t017",targetState="switch_to_disengaged",cond=whenReply("targetReached"))
					transition(edgeName="t018",targetState="switch_to_disengaged",cond=whenReply("targetUnreachable"))
				}
				state("abort_transfer") { //this:State
					action { //it:State
						// provisional failure policy (committente question 1): the transfer is aborted
						CommUtils.outred("[CARGO SERVICE] transfer aborted: the robot failed to reach a target (Q1 policy)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="switch_to_disengaged", cond=doswitch() )
				}
				state("switch_to_disengaged") { //this:State
					action { //it:State
						// discard the reservation and go back disengaged; reached from
						// completion, timeout and abort: the actions are the same
						 CurrentSlotToFill = null
						 CurrentHoldState = HoldState.DISENGAGED
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}
			}
		}
}
