/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var hold = it.unibo.hold.Hold()
		        var CurrentSlotToFillId = -1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("[CARGO SERVICE] started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGO SERVICE] DISENGAGED: waiting for load_requests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_load_request",cond=whenRequest("load_request"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("[CARGO SERVICE] evaluating load request...")
						if(  ( var CurrentHoldState = hold.getState()) != HoldState.DISENGAGED  
						 ){CommUtils.outcyan("[CARGO SERVICE] another container is being moved or the hold is 'out of service', replying with RETRY LATER.")
						answer("load_request", "load_retrylater", "load_retrylater(CurrentHoldState)"   )  
						forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name ) 
						}
						if(  (var SlotToFill = hold.nextFreeSlot()) == null  
						 ){CommUtils.outcyan("[CARGO SERVICE] all slots are taken, replying with REFUSED.")
						answer("load_request", "load_refused", "load_refused(none)"   )  
						forward("cargoservice_goto_waiting", "cargoservice_goto_waiting(none)" ,name ) 
						}
						else
						 {CommUtils.outcyan("[CARGO SERVICE] setting holdstate to ENGAGED, replying with ACCEPTED and waiting for sonar message.")
						  hold.setState(HoldState.ENGAGED)  
						  CurrentSlotToFillId = SlotToFill.getId()  
						 answer("load_request", "load_accepted", "load_accepted(CurrentSlotToFillId)"   )  
						 forward("cargoservice_goto_accept_load_request", "cargoservice_goto_accept_load_request(none)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="accept_load_request",cond=whenDispatch("cargoservice_goto_accept_load_request"))
					transition(edgeName="t02",targetState="waiting",cond=whenDispatch("cargoservice_goto_waiting"))
				}	 
				state("accept_load_request") { //this:State
					action { //it:State
						forward("checkMeasurement", "checkMeasurement(none)" ,"sonar" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_accept_load_request", 
				 	 					  scope, context!!, "local_tout_"+name+"_accept_load_request", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="switch_to_disengaged",cond=whenTimeout("local_tout_"+name+"_accept_load_request"))   
					transition(edgeName="t04",targetState="move_robot",cond=whenEvent("containerPositioned"))
					transition(edgeName="t05",targetState="set_outofservice",cond=whenEvent("outOfService"))
				}	 
				state("move_robot") { //this:State
					action { //it:State
						 hold.setSlotOccupied(CurrentSlotToFillId)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("set_outofservice") { //this:State
					action { //it:State
						 hold.setState(HoldState.OUTOFSERVICE)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("switch_to_disengaged") { //this:State
					action { //it:State
						 hold.setState(HoldState.DISENGAGED)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
