/* Generated by AN DISI Unibo */ 
package it.unibo.simled

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Simled ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var mqttIn: org.eclipse.paho.client.mqttv3.MqttClient? = null
				fun ensureSubscribed() {
					if (mqttIn != null) return
					try {
						val cli = org.eclipse.paho.client.mqttv3.MqttClient(
							"tcp://localhost:1883", "simLedIn_" + System.currentTimeMillis(),
							org.eclipse.paho.client.mqttv3.persist.MemoryPersistence())
						val opts = org.eclipse.paho.client.mqttv3.MqttConnectOptions()
						opts.isCleanSession = true
						cli.connect(opts)
						cli.subscribe("led_data") { _, message ->
							val cmd = String(message.payload).trim()
							if (cmd == "start_blinking") println("[SIM LED] *** LED BLINKING ***")
							else if (cmd == "stop_blinking") println("[SIM LED] LED off")
							else println("[SIM LED] ignored payload: " + cmd)
						}
						mqttIn = cli
					} catch (e: Exception) {
						println("[SIM LED] MQTT subscribe error: " + e.message)
					}
				}
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[SIM LED] started - subscribing to led_data")
						 ensureSubscribed()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
				state("listening") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
