/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 val StepTime = 10  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[CARGOROBOT] ready (adapter towards the external robotsmart)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="reaching",cond=whenRequest("reachTarget"))
				}	 
				state("reaching") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reachTarget(TARGETX,TARGETY)"), Term.createTerm("reachTarget(TARGETX,TARGETY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Tx = payloadArg(0)  
								 val Ty = payloadArg(1)  
								CommUtils.outyellow("[CARGOROBOT] forwarding moverobot($Tx,$Ty) to robotsmart")
								request("moverobot", "moverobot($Tx,$Ty,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="target_ok",cond=whenReply("moverobotdone"))
					transition(edgeName="t020",targetState="target_fail",cond=whenReply("moverobotfailed"))
				}	 
				state("target_ok") { //this:State
					action { //it:State
						CommUtils.outgreen("[CARGOROBOT] target reached")
						answer("reachTarget", "targetReached", "targetReached(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("target_fail") { //this:State
					action { //it:State
						CommUtils.outred("[CARGOROBOT] target unreachable")
						answer("reachTarget", "targetUnreachable", "targetUnreachable(fail)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
