/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				IDisplay display = new Display();
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outblack("[IOPORT] customer pressed pushbutton")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="accepted",cond=whenReply("load_accepted"))
					transition(edgeName="t02",targetState="retrylater",cond=whenReply("retrylater"))
					transition(edgeName="t03",targetState="refused",cond=whenReply("load_refused"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						CommUtils.outgreen("[IOPORT] DISPLAY: load_accepted received")
						if( checkMsgContent( Term.createTerm("load_accepted(SLOTID)"), Term.createTerm("load_accepted(slotId)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 display.setBookedSlot(slotId)  
								 display.setState("load accepted, system enganged")  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("retrylater") { //this:State
					action { //it:State
						CommUtils.outyellow("[IOPORT] DISPLAY: retrylater received")
						if( checkMsgContent( Term.createTerm("retrylater(HOLDSTATE)"), Term.createTerm("retrylater(CurrentHoldState)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  CurrentHoldState == HoldState.ENGAGED  
								 ){ display.setState("retry later, another request is being served...")  
								}
								else
								 { display.setState("retry later, the hold is currently out of service...")  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("refused") { //this:State
					action { //it:State
						CommUtils.outred("[IOPORT] DISPLAY: load_refused received, all slots are occupied")
						 display.setState("refused, the hold' slots are all occupied.")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
