/* Generated by AN DISI Unibo */ 
package it.unibo.simsonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Simsonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				fun loadDistances(): List<String> {
					val fallback = listOf("100","100","100","100","100","100","100","100","5","5","5","5")
					val commentChar = 35.toChar()
					return try {
						val vals = java.io.File("sonarDistances.txt").readLines()
							.map { line -> line.substringBefore(commentChar).trim() }
							.filter { line -> line.isNotEmpty() }
							.flatMap { line -> line.split(",").map { p -> p.trim() } }
							.filter { p -> p.isNotEmpty() }
						if (vals.isEmpty()) fallback else vals
					} catch (e: Exception) { fallback }
				}
				val distances = loadDistances()
				var idx = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("[SIM SONAR] started - publishing values (cyclic) on sonar_data")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="publish_one", cond=doswitch() )
				}	 
				state("publish_one") { //this:State
					action { //it:State
						 val v = distances[idx % distances.size]
								   idx = idx + 1
								   publish(v, "sonar_data")
								   println("[SIM SONAR] sonar_data <- " + v + " cm")  
						delay(1000) 
						forward("sim_next", "sim_next(none)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t026",targetState="publish_one",cond=whenDispatch("sim_next"))
				}	 
			}
		}
} 
