/* Generated by AN DISI Unibo */
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import it.unibo.Hold.*

// customer boundary: pushbutton + display. While INHIBITED (Q3) a press does not
// open a conversation: the ioport itself answers retry later on the display —
// this realizes the requirement branch "retrylater, if the IOPort is currently
// occupied by a container" (the port is dedicated for the whole operation).
class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) :
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){

				val display: IDisplay = Display()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("[IOPORT] SIMULATING PUSHBUTTON LOGIC")
						 display.setBookedSlot(-1)
						 display.setState("...")
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="simulate_pushbutton", cond=doswitch() )
				}
				state("simulate_pushbutton") { //this:State
					action { //it:State
									println("Press Enter to send load request: ")
									readln()
						 display.setBookedSlot(-1)
						 display.setState("...")
						CommUtils.outblack("[IOPORT] customer pressed pushbutton")
						request("load_request", "load_request(none)" ,"cargoservice" )
					}
					sysaction { //it:State
					}
					 transition(edgeName="t040",targetState="accepted",cond=whenReply("load_accepted"))
					transition(edgeName="t041",targetState="retrylater",cond=whenReply("load_retrylater"))
					transition(edgeName="t042",targetState="refused",cond=whenReply("load_refused"))
				}
				state("accepted") { //this:State
					action { //it:State
						CommUtils.outgreen("[IOPORT] DISPLAY: load_accepted received")
						if( checkMsgContent( Term.createTerm("load_accepted(SlotId)"), Term.createTerm("load_accepted(SlotId)"),
						                        currentMsg.msgContent()) ) { //set msgArgList
												val SlotId = payloadArg(0).toInt()
												display.setBookedSlot(SlotId)
												display.setState("load accepted, system engaged")
						}
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="inhibited", cond=doswitch() )
				}
				state("inhibited") { //this:State
					action { //it:State
						// console-simulation note: stdin is not read while inhibited, so a
						// press cannot even be typed; the retry-later evidence is on the display
						CommUtils.outyellow("[IOPORT] INHIBITED: operation in progress - a press would get: retry later")
						 display.setState("retry later, an operation is in progress")
					}
					sysaction { //it:State
					}
					 transition(edgeName="t043",targetState="simulate_pushbutton",cond=whenDispatch("enable_ioport"))
					transition(edgeName="t044",targetState="inhibited_drain",cond=whenDispatch("inhibit_ioport"))
				}
				state("inhibited_drain") { //this:State
					action { //it:State
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="inhibited", cond=doswitch() )
				}
				state("retrylater") { //this:State
					action { //it:State
						CommUtils.outyellow("[IOPORT] DISPLAY: load_retrylater received")
						if( checkMsgContent( Term.createTerm("load_retrylater(HOLDSTATE)"), Term.createTerm("load_retrylater(HOLDSTATE)"),
						                        currentMsg.msgContent()) ) { //set msgArgList
												val holdStateReceived = payloadArg(0)
												if (holdStateReceived == "engaged") {
													display.setState("retry later, another request is being served...")
												} else {
													display.setState("retry later, the hold is currently out of service...")
												}
						}
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="simulate_pushbutton", cond=doswitch() )
				}
				state("refused") { //this:State
					action { //it:State
						CommUtils.outred("[IOPORT] DISPLAY: load_refused received, all slots are occupied")
						 display.setState("refused, the hold' slots are all occupied.")
					}
					sysaction { //it:State
					}
					 transition( edgeName="goto",targetState="simulate_pushbutton", cond=doswitch() )
				}
			}
		}
}
