/* Generated by AN DISI Unibo */ 
package it.unibo.robotservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("[ROBOT SERVICE] initialized")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outmagenta("[ROBOT SERVICE] waiting for commands...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outmagenta("[ROBOT SERVICE] commanding the cargorobot to pickup the container from ioport")
						delay(5000) 
						CommUtils.outmagenta("[ROBOT SERVICE] commanding the cargorobot to move the container to slot5")
						delay(5000) 
						CommUtils.outmagenta("[ROBOT SERVICE] waiting for container to be scanned")
						delay(5000) 
						CommUtils.outmagenta("[ROBOT SERVICE] commanding the cargorobot to move the container from slot 5 to the designed slot")
						delay(5000) 
						CommUtils.outmagenta("[ROBOT SERVICE] commanding the cargorobot to move back to HOME")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
